name: Test Package

on:
  push:

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1

      - run: npm ci
      - run: npm install
      - run: npm test
